"""initial schema

Revision ID: 57a436aed52a
Revises: 
Create Date: 2026-04-11 08:08:57.158147
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '57a436aed52a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
